### ISSUE TITLE
false positive for the first word of every newline 

### ISSUE THREAD

**Issue by itsrimzz1** [pirtleshell/codemirror-typo#1]
![image](https://cloud.githubusercontent.com/assets/25577826/23889648/1f87a9f0-08b4-11e7-8e1e-32edd430eb7e.png)

For the very first word in every new line i am getting a false positive. it does get resolved if i start the line with a space. Can you tell me the reason for this behaviour and how i can resolve it.

my current config of codeMirrorTypo object is:

`
let codeMirrorTypoOptions = {
      dictPath: 'https://raw.githubusercontent.com/titoBouzout/Dictionaries/master/',
      dictFolder: '',                           

      filename: 'English (American)',                             
      typoClass: 'typo',                         
                                                
      typoCSS: 'border-bottom: 1px dotted red;',  
      gutterClass: 'test2',                 
      gutterMarkClass: 'test2',              
    }

codeMirrorTypo(this.codeMirror, 'English (American)', codeMirrorTypoOptions);

`

**Comment by pirtleshell** [comment]
Sorry for the delay, did you get this to work?

I haven't been actively maintaining this repo, because I've found that on newer browsers there is a faster solution that makes use of the built-in spellcheck on the browser.

I'd have to double check the specifics, but I recall it being as simple as instantiating your CodeMirror instance with these options:
```js
{
  spellcheck: true,
  inputStyle: 'contenteditable'
}
```

It puts `contenteditable` on the line divs, so the browser knows to spellcheck them.
